microapp:
  microId: grant-bff
server:
  port: 9081
  servlet:
    context-path: /grant-bff
    
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html  
    
 
#logging:
#  pattern:
#    level: 'trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p'
    
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:4318/v1/metrics
#        step: 10s
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#      export:
#        step: 10s # Export interval set to 10 seconds
  tracing:
    sampling:
      probability: 1.0     
    
service:
  auth-base-uri: http://localhost:9080/grant-service
  
restTemplate:
  connectionPool:
    maxPerRoute: 10
    maxConnections: 10 
    
spring:   
  application:
    name: grant-bff
  cloud:
    gateway:
      mvc:
        routes:
          - id: grant-service
            uri: lb://grant-service
            predicates:
              - Path=/grant-service/**
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
  
